#include <stdio.h>

int main() {
    // Declare a character variable
    char c;

    // Ask the user to enter characters
    printf("Enter characters (Ctrl+D to end on Unix/Linux or Ctrl+Z on Windows):\n");


    c = getchar(); // Read a character from standard input
    while (c != EOF) { // Continue until end of file
        putchar(c); // Write the character to standard output
        c = getchar(); // Read the next character
    }
    // Note: EOF is a special value indicating the end of input
    // It is typically generated by pressing Ctrl+D (on Unix/Linux) or Ctrl+Z (on Windows) in the terminal.
    
    // End of file reached, return 0 to indicate successful completion
    printf("\nEnd of file reached.\n");

    return 0;
}